config/routes.rb
Rails.application.routes.draw do
  resources :communities
  resources :species_families
  resources :species
  resources :locations
  resources :field_data
  resources :projects
  resources :welcomes
  devise_for :companies
  devise_for :admins
  devise_for :users
  get '/sign_out' => 'devise/sessions#destroy'
  controller :export do
    get 'export/companies/' => :export_companies
    get 'export/projects/' => :export_projects
    get 'export/field_data/' => :export_field_data
    get 'export/observations/' => :export_observations
    get 'export/growth_forms/' => :export_growth_forms
    get 'export/crown_diameter/' => :export_crown_diameter
    get 'export/plant_cover/' => :export_plant_cover
    get 'export/communities/' => :export_communities
    get 'export/species_families/' => :export_species_families
    get 'export/community_growth_forms/' => :export_community_growth_forms
    get 'export/report_communities/' => :export_report_communities
    get 'export/community_covers/' => :export_community_covers

    post 'export/companies/' => :export_companies
    post 'export/projects/' => :export_projects
    post 'export/field_data/' => :export_field_data
    post 'export/observations/' => :export_observations
    post 'export/growth_forms/' => :export_growth_forms
    post 'export/crown_diameter/' => :export_crown_diameter
    post 'export/plant_cover/' => :export_plant_cover
    post 'export/communities/' => :export_communities
    post 'export/species_families/' => :export_species_families
    post 'export/community_growth_forms/' => :export_community_growth_forms
    post 'export/report_communities/' => :export_report_communities
    post 'export/community_covers/' => :export_community_covers

  end
  controller :import do
    get 'import/show/' => :import_data_path
    post 'import/show/' => :import_data_path
  end
  controller :reports do
    get 'new/species/report/'   => :new_species_report
    post 'create/species/report/'   => :create_species_report
    get 'create/species/report/'   => :create_species_report
    get 'new/community_cover/report/'   => :new_community_cover_report
    post 'create/community_cover/report/'   => :create_community_cover_report
    get 'create/community_cover/report/'   => :root
    get 'new/comparative_growth/report/'   => :new_comparative_growth_report
    post 'create/comparative_growth/report/'   => :create_comparative_growth_report
    get 'create/comparative_growth/report/'   => :root
    get 'new/community_composition/report/'   => :new_community_composition_report
    post 'create/community_composition/report/'   => :create_community_composition_report
    get 'create/community_composition/report/'   => :root
    get 'all/field_data//'   => :all_field_data
  end
  controller :manage do
    get 'manage/users'   => :users
    get 'edit/user/:id'   => :edit_user
    get 'edit/user/password/:id'   => :edit_user_password
    get 'new/user/'   => :new_user
    post 'create/user/'   => :create_user
    get 'delete/user/:id'   => :delete_user
    patch 'update/user/:id'   => :update_user
    patch 'update/user/password/:id'   => :update_user_password
    get 'manage/companies'     => :companies
    get 'edit/company/:id'   => :edit_company
    get 'edit/company/password/:id'   => :edit_company_password
    get 'delete/company/:id'   => :delete_company
    get 'new/company/'   => :new_company
    post 'create/company/'   => :create_company
    patch 'update/company/:id'   => :update_company
    patch 'update/company/password/:id'   => :update_company_password
  end

  root 'welcomes#index'

end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]
  before_action :deny_to_admins_and_companies

  # GET /species
  # GET /species.json
  def index
    @species = Species.order(:name)
    # @species.each do|s|
    #   s.delete
    # end
  end

  # GET /species/1
  # GET /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy

    @species.destroy
    respond_to do |format|
      format.html { redirect_to species_index_url, notice: 'Species was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def species_params
      params.require(:species).permit(:name, :potential_biomass, :species, :threat_status, :sa_endemic, :sysnonym_of, :common_name, :life_cycle, :growth_forms, :min_hieght, :max_height, :min_altitude, :max_altitude, :distribution,:species_family_id)
    end

    def deny_to_admins_and_companies
      redirect_to new_user_session_path unless user_signed_in?
    end

end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/species/_form.html.haml
= form_for @species do |f|
  - if @species.errors.any?
    #error_explanation
      %h2= "#{pluralize(@species.errors.count, "error")} prohibited this species from being saved:"
      %ul
        - @species.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field
    = f.label :potential_biomass
    = f.text_field :potential_biomass, class: "form-control"
  .field
    = f.label :species_family_id
    = f.collection_select(:species_family_id, SpeciesFamily.order('name ASC').all, :id, :name, {}, {:class=>'form-control'})
  .field
    = f.label :threat_status
    = f.text_field :threat_status, class: "form-control"
  .field
    = f.label :sa_endemic
    = f.text_field :sa_endemic, class: "form-control"
  .field
    %label
      Synonym of
    = f.text_field :sysnonym_of, class: "form-control"
  .field
    = f.label :common_name
    = f.text_field :common_name, class: "form-control"
  .field
    = f.label :life_cycle
    = f.text_field :life_cycle, class: "form-control"
  .field
    = f.label :growth_forms
    = f.text_field :growth_forms, class: "form-control"
  .field
    = f.label :min_hieght
    = f.text_field :min_hieght, class: "form-control"
  .field
    = f.label :max_height
    = f.text_field :max_height, class: "form-control"
  .field
    = f.label :min_altitude
    = f.text_field :min_altitude, class: "form-control"
  .field
    = f.label :max_altitude
    = f.text_field :max_altitude, class: "form-control"
  .field
    = f.label :distribution
    = f.text_field :distribution, class: "form-control"
  .clear-20
  .actions
    = f.submit 'Save', class: "btn btn-success pull-right"

app/views/species/edit.html.haml
%h1.page-header
  Editing
  %small
    species
.col-lg-10
  = render 'form'
  = link_to 'Show', @species, class: "btn btn-primary"
  = link_to 'Back', species_index_path, class: "btn btn-default"

app/views/species/index.html.haml
%h1.page-header
  Listing
  %small
    species
= link_to '<i class="fa fa-plus"></i> New Species'.html_safe, new_species_path, class: "btn btn-success pull-right"
%table.table
  %thead
    %tr
      %th Name
      %th Species Family
      %th
      %th
      %th

  %tbody
    - @species.each do |species|
      %tr
        %td= species.name
        -if SpeciesFamily.exists?(species.species_family_id)
          %td= species.species_family.name
        %td= link_to 'Show', species, class:  "btn btn-default"
        %td= link_to 'Edit', edit_species_path(species), class:  "btn btn-primary"
        -# %td= link_to 'Destroy', species, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:  "btn btn-danger"

%br

app/views/species/new.html.haml
%h1.page-header
  New
  %small
    species
.col-lg-10
  = render 'form'
  = link_to 'Back', species_index_path, class: "btn btn-default"

app/views/species/show.html.haml
%h1.page-header
  Showing
  %small
    = @species.name
%h4
  %b Name:
  = @species.name
%h4
  %b Potential biomass:
  = @species.potential_biomass
%h4
  %b Species family:
  = @species.species_family.name
%h4
  %b Threat status:
  = @species.threat_status
%h4
  %b Sa endemic:
  = @species.sa_endemic
%h4
  %b Synonym of:
  = @species.sysnonym_of
%h4
  %b Common name:
  = @species.common_name
%h4
  %b Life cycle:
  = @species.life_cycle
%h4
  %b Growth forms:
  = @species.growth_forms
%h4
  %b Min hieght:
  = @species.min_hieght
%h4
  %b Max height:
  = @species.max_height
%h4
  %b Min altitude:
  = @species.min_altitude
%h4
  %b Max altitude:
  = @species.max_altitude
%h4
  %b Distribution:
  = @species.distribution

= link_to 'Edit', edit_species_path(@species), class: "btn btn-primary"

= link_to 'Back', species_index_path, class: "btn btn-default"