config/routes.rb
Rails.application.routes.draw do
  resources :communities
  resources :species_families
  resources :species
  resources :locations
  resources :field_data
  resources :projects
  resources :welcomes
  devise_for :companies
  devise_for :admins
  devise_for :users
  get '/sign_out' => 'devise/sessions#destroy'
  controller :export do
    get 'export/companies/' => :export_companies
    get 'export/projects/' => :export_projects
    get 'export/field_data/' => :export_field_data
    get 'export/observations/' => :export_observations
    get 'export/growth_forms/' => :export_growth_forms
    get 'export/crown_diameter/' => :export_crown_diameter
    get 'export/plant_cover/' => :export_plant_cover
    get 'export/communities/' => :export_communities
    get 'export/species_families/' => :export_species_families
    get 'export/community_growth_forms/' => :export_community_growth_forms
    get 'export/report_communities/' => :export_report_communities
    get 'export/community_covers/' => :export_community_covers

    post 'export/companies/' => :export_companies
    post 'export/projects/' => :export_projects
    post 'export/field_data/' => :export_field_data
    post 'export/observations/' => :export_observations
    post 'export/growth_forms/' => :export_growth_forms
    post 'export/crown_diameter/' => :export_crown_diameter
    post 'export/plant_cover/' => :export_plant_cover
    post 'export/communities/' => :export_communities
    post 'export/species_families/' => :export_species_families
    post 'export/community_growth_forms/' => :export_community_growth_forms
    post 'export/report_communities/' => :export_report_communities
    post 'export/community_covers/' => :export_community_covers

  end
  controller :import do
    get 'import/show/' => :import_data_path
    post 'import/show/' => :import_data_path
  end
  controller :reports do
    get 'new/species/report/'   => :new_species_report
    post 'create/species/report/'   => :create_species_report
    get 'create/species/report/'   => :create_species_report
    get 'new/community_cover/report/'   => :new_community_cover_report
    post 'create/community_cover/report/'   => :create_community_cover_report
    get 'create/community_cover/report/'   => :root
    get 'new/comparative_growth/report/'   => :new_comparative_growth_report
    post 'create/comparative_growth/report/'   => :create_comparative_growth_report
    get 'create/comparative_growth/report/'   => :root
    get 'new/community_composition/report/'   => :new_community_composition_report
    post 'create/community_composition/report/'   => :create_community_composition_report
    get 'create/community_composition/report/'   => :root
    get 'all/field_data//'   => :all_field_data
  end
  controller :manage do
    get 'manage/users'   => :users
    get 'edit/user/:id'   => :edit_user
    get 'edit/user/password/:id'   => :edit_user_password
    get 'new/user/'   => :new_user
    post 'create/user/'   => :create_user
    get 'delete/user/:id'   => :delete_user
    patch 'update/user/:id'   => :update_user
    patch 'update/user/password/:id'   => :update_user_password
    get 'manage/companies'     => :companies
    get 'edit/company/:id'   => :edit_company
    get 'edit/company/password/:id'   => :edit_company_password
    get 'delete/company/:id'   => :delete_company
    get 'new/company/'   => :new_company
    post 'create/company/'   => :create_company
    patch 'update/company/:id'   => :update_company
    patch 'update/company/password/:id'   => :update_company_password
  end

  root 'welcomes#index'

end

app/models/community.rb
class Community < ActiveRecord::Base
  belongs_to :project
  belongs_to :project_report
  validates :project, presence: true
  validates :description, presence: true
  has_many :report_communities, dependent: :destroy
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    projects = Project.where(company_id:current_user.company_id)
    @communities = Community.where(project: projects)
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:description, :project_id)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.haml
= form_for @community do |f|
  - if @community.errors.any?
    #error_explanation
      %h2= "#{pluralize(@community.errors.count, "error")} prohibited this community from being saved:"
      %ul
        - @community.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :project_id
    = f.collection_select(:project_id, Project.where(company_id:current_user.company_id), :id, :name, {}, {:class=>'form-control'})
  .field
    %label Description
    = f.text_field :description, class: "form-control"
  .clear-20
  .actions
    = f.submit 'Save', class: "btn btn-success pull-right"

app/views/communities/edit.html.haml
%h1.page-header
  Editing
  %small
    Community
.col-lg-10
  = render 'form'

  = link_to 'Show', @community, class: "btn btn-primary"
  = link_to 'Back', communities_path, class: "btn btn-default"

app/views/communities/index.html.haml
%h1.page-header
  Listing
  %small
    Communities
= link_to '<i class="fa fa-plus"></i> New Community'.html_safe, new_community_path, class: "btn btn-success pull-right"

%table.table
  %thead
    %tr
      %th Project
      %th Description
      %th
      %th
      %th

  %tbody
    - @communities.each do |community|
      %tr
        %td= community.project.name
        %td= community.description
        %td= link_to 'Show', community, class: "btn btn-default"
        %td= link_to 'Edit', edit_community_path(community), class: "btn btn-primary"
        -# %td= link_to 'Destroy', community, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"
%br

app/views/communities/new.html.haml
%h1.page-header
  New
  %small
    Community
.col-lg-10
  = render 'form'
  = link_to 'Back', communities_path, class: "btn btn-default"

app/views/communities/show.html.haml
%h1.page-header
  Showing
  %small
    Community
%h4
  %b Project:
  = @community.project.name
%h4
  %b Description:
  = @community.description
= link_to 'Edit', edit_community_path(@community),class:"btn btn-primary"
= link_to 'Back', communities_path,class:"btn btn-default"