config/routes.rb
Rails.application.routes.draw do
  resources :communities
  resources :species_families
  resources :species
  resources :locations
  resources :field_data
  resources :projects
  resources :welcomes
  devise_for :companies
  devise_for :admins
  devise_for :users
  get '/sign_out' => 'devise/sessions#destroy'
  controller :export do
    get 'export/companies/' => :export_companies
    get 'export/projects/' => :export_projects
    get 'export/field_data/' => :export_field_data
    get 'export/observations/' => :export_observations
    get 'export/growth_forms/' => :export_growth_forms
    get 'export/crown_diameter/' => :export_crown_diameter
    get 'export/plant_cover/' => :export_plant_cover
    get 'export/communities/' => :export_communities
    get 'export/species_families/' => :export_species_families
    get 'export/community_growth_forms/' => :export_community_growth_forms
    get 'export/report_communities/' => :export_report_communities
    get 'export/community_covers/' => :export_community_covers

    post 'export/companies/' => :export_companies
    post 'export/projects/' => :export_projects
    post 'export/field_data/' => :export_field_data
    post 'export/observations/' => :export_observations
    post 'export/growth_forms/' => :export_growth_forms
    post 'export/crown_diameter/' => :export_crown_diameter
    post 'export/plant_cover/' => :export_plant_cover
    post 'export/communities/' => :export_communities
    post 'export/species_families/' => :export_species_families
    post 'export/community_growth_forms/' => :export_community_growth_forms
    post 'export/report_communities/' => :export_report_communities
    post 'export/community_covers/' => :export_community_covers

  end
  controller :import do
    get 'import/show/' => :import_data_path
    post 'import/show/' => :import_data_path
  end
  controller :reports do
    get 'new/species/report/'   => :new_species_report
    post 'create/species/report/'   => :create_species_report
    get 'create/species/report/'   => :create_species_report
    get 'new/community_cover/report/'   => :new_community_cover_report
    post 'create/community_cover/report/'   => :create_community_cover_report
    get 'create/community_cover/report/'   => :root
    get 'new/comparative_growth/report/'   => :new_comparative_growth_report
    post 'create/comparative_growth/report/'   => :create_comparative_growth_report
    get 'create/comparative_growth/report/'   => :root
    get 'new/community_composition/report/'   => :new_community_composition_report
    post 'create/community_composition/report/'   => :create_community_composition_report
    get 'create/community_composition/report/'   => :root
    get 'all/field_data//'   => :all_field_data
  end
  controller :manage do
    get 'manage/users'   => :users
    get 'edit/user/:id'   => :edit_user
    get 'edit/user/password/:id'   => :edit_user_password
    get 'new/user/'   => :new_user
    post 'create/user/'   => :create_user
    get 'delete/user/:id'   => :delete_user
    patch 'update/user/:id'   => :update_user
    patch 'update/user/password/:id'   => :update_user_password
    get 'manage/companies'     => :companies
    get 'edit/company/:id'   => :edit_company
    get 'edit/company/password/:id'   => :edit_company_password
    get 'delete/company/:id'   => :delete_company
    get 'new/company/'   => :new_company
    post 'create/company/'   => :create_company
    patch 'update/company/:id'   => :update_company
    patch 'update/company/password/:id'   => :update_company_password
  end

  root 'welcomes#index'

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid.z-index
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to image_tag("zingela_logo.png",:class => 'navbar-brand'), root_path
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
      %ul.nav.navbar-nav.navbar-right
        = render "layouts/login_nav"
  -if notice
    .alert.alert-success.alert-dismissibl{:role => "alert"}
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      = notice
  -if alert
    .alert.alert-danger.alert-dismissible{:role => "alert"}
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      = alert
  %ul.nav.navbar-nav.side-nav
    - if admin_signed_in?
      %li
        =link_to 'New Company', new_company_path
      %li
        =link_to 'Manage Companies', manage_companies_path
      %li
        =link_to 'New User', new_user_path
      %li
        =link_to 'Manage Users', manage_users_path
    - if user_signed_in?
      = render "layouts/user_nav"

app/views/layouts/_login_nav.html.haml
- if admin_signed_in?
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %i.fa.fa-user
      =current_admin.email
      %b.caret
    %ul.dropdown-menu
      %li
        =link_to 'Logout <i class="fa fa-fw fa-power-off"></i>'.html_safe, destroy_admin_session_path, :method => :delete
- if user_signed_in?
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %i.fa.fa-user
      =current_user.email
      %b.caret
    %ul.dropdown-menu
      %li
        %a{:href => "/", :onclick => "return false;"}
          = Company.find(current_user.company_id).company_name
          %i.fa.fa-building
      %li
        =link_to 'Logout <i class="fa fa-fw fa-power-off"></i>'.html_safe, destroy_user_session_path, :method => :delete
- user_active = ""
- admin_active = ""
- is_login_screen = ""
- if request.original_url.include? "admins/sign_in"
  - admin_active = "active"
  - is_login_screen = true
- if request.original_url.include? "users/sign_in"
  - user_active = "active"
  - is_login_screen = true
- if is_login_screen == true
  %ul.nav.nav-pills.pull-right
    %li{:role => "presentation", :class => "#{user_active}"}
      %a{:href => "/users/sign_in/"} User Login
    %li{:role => "presentation", :class => "#{admin_active}"}
      %a{:href => "/admins/sign_in/"} Admin Login

app/views/layouts/_user_nav.html.haml
%li
  %a{"data-target" => "#projects", "data-toggle" => "collapse", :href => "javascript:;"}
    %i.fa.fa-files-o
    Projects
    %i.fa.fa-fw.fa-caret-down
  %ul#projects.collapse
    %li
      =link_to 'New <i class="fa fa-fw fa-plus"></i>'.html_safe, new_project_path
    %li
      =link_to 'Manage <i class="fa fa-fw fa-pencil"></i>'.html_safe, projects_path
%li
  %a{"data-target" => "#field_data", "data-toggle" => "collapse", :href => "javascript:;"}
    %i.fa.fa-database
    Field Data
    %i.fa.fa-fw.fa-caret-down
  %ul#field_data.collapse
    %li
      =link_to 'New <i class="fa fa-fw fa-plus"></i>'.html_safe, new_field_datum_path
    %li
      =link_to 'Manage <i class="fa fa-fw fa-pencil"></i>'.html_safe, field_data_path
%li
  %a{"data-target" => "#species_family", "data-toggle" => "collapse", :href => "javascript:;"}
    %i.fa.fa-globe
    Species Family
    %i.fa.fa-fw.fa-caret-down
  %ul#species_family.collapse
    %li
      =link_to 'New <i class="fa fa-fw fa-plus"></i>'.html_safe, new_species_family_path
    %li
      =link_to 'Manage <i class="fa fa-fw fa-pencil"></i>'.html_safe,  species_families_path
%li
  %a{"data-target" => "#species", "data-toggle" => "collapse", :href => "javascript:;"}
    %i.fa.fa-pagelines
    Species
    %i.fa.fa-fw.fa-caret-down
  %ul#species.collapse
    %li
      =link_to 'New <i class="fa fa-fw fa-plus"></i>'.html_safe, new_species_path
    %li
      =link_to 'Manage <i class="fa fa-fw fa-pencil"></i>'.html_safe,  species_index_path
%li
  %a{"data-target" => "#communities", "data-toggle" => "collapse", :href => "javascript:;"}
    %i.fa.fa-users
    Communities
    %i.fa.fa-fw.fa-caret-down
  %ul#communities.collapse
    %li
      =link_to 'New <i class="fa fa-fw fa-plus"></i>'.html_safe, new_community_path
    %li
      =link_to 'Manage <i class="fa fa-fw fa-pencil"></i>'.html_safe, communities_path
%li
  %a{"data-target" => "#report", "data-toggle" => "collapse", :href => "javascript:;"}
    %i.fa.fa-file-text-o
    Reports
    %i.fa.fa-fw.fa-caret-down
  %ul#report.collapse
    %li
      =link_to 'Community cover report'.html_safe, new_community_cover_report_path
    %li
      =link_to 'Community composition report'.html_safe, new_community_composition_report_path
    %li
      =link_to 'Comparative growth report'.html_safe, new_comparative_growth_report_path
    %li
      =link_to 'Species report'.html_safe, create_species_report_path
%li
  %a{"data-target" => "#imports", "data-toggle" => "collapse", :href => "javascript:;"}
    %i.fa.fa-file-text-o
    Exports
    %i.fa.fa-fw.fa-caret-down
  %ul#imports.collapse
    %li
      =link_to 'Species Family'.html_safe, export_species_families_path
    %li
      =link_to 'Companies'.html_safe, export_companies_path
    %li
      =link_to 'Projects'.html_safe, export_projects_path
    %li
      =link_to 'Communities'.html_safe, export_communities_path
    %li
      =link_to 'Field Data'.html_safe, export_field_data_path
    %li
      =link_to 'Observations'.html_safe, export_observations_path
    %li
      =link_to 'Growth forms'.html_safe, export_growth_forms_path
    %li
      =link_to 'Crown Diameter'.html_safe, export_crown_diameter_path
    %li
      =link_to 'Plant Cover'.html_safe, export_plant_cover_path
    %li
      =link_to 'Community Growth Forms'.html_safe, export_community_growth_forms_path
    %li
      =link_to 'Report Communities'.html_safe, export_report_communities_path
    %li
      =link_to 'Community Covers'.html_safe, export_community_covers_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Zingela
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css", :rel => "stylesheet"}/

    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", :type => "text/javascript"}
    %script{:src => "http://code.jquery.com/ui/1.11.4/jquery-ui.min.js", :type => "text/javascript"}
    %script{:src => "https://raw.github.com/xuanluo/flot-axislabels/master/jquery.flot.axislabels.js"}
  %body
    = render "layouts/header"
    #wrapper
      #page-wrapper
        .container-fluid
          = yield